services:
  challenges:
    image: app-challenges
    ports:
      - "3000:3500"
  flashcards:
    image: app-flashcards
    ports:
      - "3100:3500"
  notes:
    image: app-notes
    environment:
        - "AUTH_URL=http://app-users:3500"
    ports:
      - "3200:3500"
  users:
    image: app-users
    ports:
      - "3300:3500"
